### ISSUE TITLE
Already bricked 4 plus1 and 1 plus1pm with OTA

### ISSUE THREAD

**Issue by Klaus3d3** [phiten/mgos32-to-tasmota32#21] opened 2023-07-27 14:29 UTC
Hello, sadly i have the same issue as described below.

All starting from 0.14.1

_Originally posted by @Klaus3d3 in https://github.com/phiten/mgos32-to-tasmota32/issues/14#issuecomment-1652506845_

**Comment by phiten** [comment] 2023-07-27 14:35
As I already wrote in the other issue I can't reproduce any of the problems. Whenever I test it works perfectly fine.

So without an affected device on my bench there is no way for me to test it sorry.

**Comment by Klaus3d3** [comment] 2023-07-28 18:08
Now i tried a fresh Shelly plus 1 flashing via UART Adapter and its still the same result. Flashing went through like butter without any error. But the result is the same. I was also able to flash tasmota to a bricked shelly, but also the same result. No Wifi or BT

**Comment by Klaus3d3** [comment] 2023-07-28 18:14
Edit: 1 is back to life! :-D

Seems to work now via UART/Serial. But here i also need to flash twice.

**Comment by phiten** [comment] 2023-07-29 09:51
If you flash via UART you can use the tasmota image directly. No need for the conversion image.

I just tried the update again and it worked flawless. So I'm going to close this issue as it is not reproducible by me.

**Closed as completed** 2023-07-29 09:51 UTC
